apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodek8s
  name: nodek8s
  namespace: fiuber-ns
spec:
  selector:
    app: nodek8s
  type: NodePort
  sessionAffinity: None
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5800

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nodek8s
  namespace: fiuber-ns
  labels:
    app:  nodek8s
spec:
  selector:
    matchLabels:
      app: nodek8s
  replicas: 1
  template:
    metadata:
      name: nodek8s
      labels:
        app:  nodek8s
    spec:
      containers:
      - name:  nodek8s
        image:  cqueirolo/nodek8s
        ports:
        - name:  http
          containerPort: 5800
          protocol: TCP
